### ISSUE TITLE
Please provide links to documentation.

### ISSUE THREAD

**Issue by gl-yziquel** [SWI-Prolog/packages-swipy#11]
The README.md file on the packages-swipy mentions using janus as a library in prolog. However, it does not provide links to documentation. This makes it hard for a newcommer.

A link in the readme would be welcome.

**Comment by gl-yziquel** [comment]
Here ?

https://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/janus.html%27)

**Comment by JanWielemaker** [comment]
Thanks.    More links are often a good idea :) There was a subsection with a link to the docs.     Moved that to the start.
