### ISSUE TITLE
Arguments are not sufficiently instantiated error when asserting variables

### ISSUE THREAD

**Issue by damianoazzolini** [SWI-Prolog/packages-swipy#15]
Hi,
I'm using Janus version 1.4.0 embedding SWI-Prolog 9.2.8.
When I try asserting, via janus, a term with a variable inside, I get an `Arguments are not sufficiently instantiated` error, while, if I do so directly in the SWI REPL, I get true (as expected). This does not happen when the anonymous variable is used.

For example:
```
>>> import janus_swi as janus
>>> janus.query_once("assert(a(X))")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/damiano/anaconda3/lib/python3.9/site-packages/janus_swi/janus.py", line 245, in query_once
    return _swipl.call(query, inputs, keep)
janus_swi.janus.PrologError: '$c_call_prolog'/0: Arguments are not sufficiently instantiated
>>> janus.query_once("assert(a(_))")
{'truth': True}
```
while within the SWI repl I get
```
?- assert(a(_)).
true.

?- assert(a(A)).
true.
```
Is this a bug or an intended behaviour? This would be good to have to, for example, asserting dynamic rules at runtime.

**Comment by JanWielemaker** [comment]
Please use Discourse for questions (https://swi-prolog.discourse.group/).   And no, this is not a bug.  It will return a dict holding the variable bindings, but as you do not bind `A` and variables have no sensible meaning in Python, you get this error.   Use `"assert(a(_))"` or `"assert(a(_X))"` to prevent returning the variable.

There is more to say about this, for example why you want this and whether there are not better alternatives as in `janus.consult()`.   That is for Discourse.
