### ISSUE TITLE
Error when run examples/trains.py

### ISSUE THREAD

**Issue by dxbdxx** [SWI-Prolog/packages-swipy#3]
janus_swi/janus.py", line 186, in __next__
    if rc == False or rc["truth"] == False:
KeyError: 'truth'

**Comment by JanWielemaker** [comment]
Thanks for reporting.   Works fine if you re-install the janus_swi Python package using pip (using the latest git version of this repo).   The success/failure/undefined key for the result dict changed from `status` to `truth` as a result of standardization discussions.    In the details, Janus is  a moving target as long as the dust of these discussions has not settled.  We are close!
