### ISSUE TITLE
Can't catch PrologError

### ISSUE THREAD

**Issue by kamahen** [SWI-Prolog/packages-swipy#9]
To demonstrate this, change `demo.py` `test_invalid_nesting()` from `catch Exception` to `catch PrologError`. 
What's puzzling is that 
`catch Exception as exc: print(repr(str))`, 
outputs 
`PrologError(swipl.next_solution(): not inner query)`.

(You can assign this to me)

**Comment by kamahen** [comment]
BTW, `PrologError` should probably derive from `RuntimeError`. See https://docs.python.org/3/library/exceptions.html#exception-hierarchy

**Comment by maluff** [comment]
A possible fix to this issue is changing the following line https://github.com/SWI-Prolog/packages-swipy/blob/0b0e97b68257c9faa90b8830afe508896006fb9f/janus/mod_swipl.c#L73 to  `PyErr_SetObject(constructor, ex);`. This will create the respective exception class instead of a second, equally named one.

**Comment by JanWielemaker** [comment]
Thanks.   That works.     If I understand you correctly I created two exception classes, one from C and one in Python.    Thanks for spotting!

> `PrologError(swipl.next_solution(): not inner query)`.

That did not reproduce for me, but this issue has not been addressed and might this be still relevant.

Published to PyPi as 1.2.1.    Also fixes a GIL issue in `py_object/1` that surfaced in the tests after moving to Fedora Linux.

**Comment by kamahen** [comment]
Confirmed that this fixes the problem (and thank-you for understanding my badly written bug report).

I will add some tests for this when I make the PR for adding context manager support (also some changes to the documentation and demo code).
